### ISSUE TITLE
Discussing the core functionality of being able to make a domain as incognito only

### ISSUE THREAD

**Issue by vipulbhj** [fxnoob/mark-incognito#2]

**Comment by vipulbhj** [comment]
@fxnoob What will be best way forward ??

**Comment by fxnoob** [comment]
I suppose this should be the way::-
1. Click on the extension icon . it will open an option page
2. Do entry of the url you want to open automatically in incognito mode.   

also there would be an option on context menu of browser to include/exclude current opened website

**Comment by vipulbhj** [comment]
Lets start with having a toggle button in the browsers menu which will open up the extension view, where with a toggle you can mark and unmark, the current visited domain as incognito listed or not
