### ISSUE TITLE
Exact Url Match Issue

### ISSUE THREAD

**Issue by vipulbhj** [fxnoob/mark-incognito#21]
The current implementation of url interception uses exact url match which has the issue of query parameter. For example say a url looks something like `https://www.example.com/the-random-blog?q=safe&trackingId=14265212798`, the expected behaviour will mark incognito to the url without query parameters but the current implementation doesn't work in I just use `https://www.example.com/the-random-blog`. 

## Current Behaviour :-
Exact Url match is performed on all urls. 

## Expected Behaviour :- 
urls when saved should remove all url parameters and while intercepting, it should also filter for the same.

**Comment by carlosnufe** [comment]
Can I help with this?

**Comment by vipulbhj** [comment]
@carlosnufe we have a PR for this already in place but we would love for you to keep around and check for any other issues

**Comment by carlosnufe** [comment]
> @carlosnufe we have a PR for this already in place but we would love for you to keep around and check for any other issues

Sorry, I didn't see it. Let's check out the other issues 🤓

**Comment by vipulbhj** [comment]
@fxnoob what changes were you suggesting here ???

**Comment by fxnoob** [comment]
@vipulbhj , pls see your pull request. I've commented there.
